# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.0.0"

# Update k8s.io constraints once kubernetes-1.14.0 is cut such that it
# selects 1.14.0 (k8s.io/kubernetes) resp. kubernetes-1.14.0 (everything else).
[[constraint]]
  name = "k8s.io/api"
  branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "master"

# For E2E framework.
[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "master"

# Dependencies of E2E framework, versions must match k8s.io/kubernetes.
[[override]]
  name = "k8s.io/apimachinery"
  branch = "master"
[[override]]
  name = "k8s.io/api"
  branch = "master"
[[override]]
  name = "k8s.io/apiserver"
  branch = "master"
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "master"
[[override]]
  name = "k8s.io/cli-runtime"
  branch = "master"
[[override]]
  name = "k8s.io/client-go"
  branch = "master"
[[override]]
  name = "k8s.io/cloud-provider"
  branch = "master"
[[override]]
  name = "k8s.io/cluster-bootstrap"
  branch = "master"
[[override]]
  name = "k8s.io/csi-api"
  branch = "master"
[[override]]
  name = "k8s.io/kube-aggregator"
  branch = "master"

# Doesn't do proper releases.
[[override]]
  name = "k8s.io/kube-openapi"
  branch = "master"

# Also no proper releases.
[[override]]
  name = "k8s.io/utils"
  branch = "master"

# Remove once some version with AccumulatedCopySizeLimit is published.
# Kubernetes depends on >v4.1.0-19-g5858425f75500d
[[override]]
  name = "github.com/evanphx/json-patch"
  branch = "master"

# Remove once 0.4.0 is cut
[[constraint]]
  name = "github.com/kubernetes-csi/csi-lib-utils"
  version = ">=0.4.0-rc1"

# https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"


[prune]
   non-go = true
   go-tests = true
   unused-packages = true
