# This YAML file demonstrates how to deploy the external
# provisioner for use with the mock CSI driver. It
# depends on the RBAC definitions from rbac.yaml.

kind: Service
apiVersion: v1
metadata:
  name: csi-cluster-driver-registrar
  labels:
    app: csi-cluster-driver-registrar
spec:
  selector:
    app: csi-cluster-driver-registrar
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-cluster-driver-registrar
spec:
  serviceName: "csi-cluster-driver-registrar"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-cluster-driver-registrar
    spec:
      serviceAccount: csi-cluster-driver-registrar
      terminationGracePeriodSeconds: 10
      containers:
        - name: cluster-driver-registrar
          image: quay.io/k8scsi/csi-cluster-driver-registrar:canary
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: mock-driver
          image: quay.io/k8scsi/mock-driver:v1.1.1
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir:
